package iuh.fit.infrastructure.network;

public enum CommandType {
    // Giao ca
    GET_CA_DANG_LAM, NHAN_CA, GIAO_CA,

    // Authentication
    LOGIN,

    // Phòng
    GET_ALL_PHONG, GET_PHONG_BY_ID, GET_PHONG_BY_TINH_TRANG,
    GET_PHONG_BY_MA_LOAI_PHONG, ADD_PHONG, UPDATE_PHONG, DELETE_PHONG,
    FIND_AVAILABLE_ROOMS,

    // Khách hàng
    GET_ALL_KHACH_HANG, GET_KHACH_HANG_BY_ID, GET_KHACH_HANG_BY_SDT,
    ADD_KHACH_HANG, UPDATE_KHACH_HANG, DELETE_KHACH_HANG,

    // Phiếu đặt phòng
    GET_ALL_PHIEU_DAT_PHONG, GET_PHIEU_DAT_PHONG_BY_ID,
    GET_PHIEU_DAT_PHONG_BY_KHACH_HANG, GET_PHIEU_DAT_PHONG_BY_PHONG,
    GET_PHIEU_DAT_PHONG_IN_DATE_RANGE,
    ADD_PHIEU_DAT_PHONG, UPDATE_PHIEU_DAT_PHONG, DELETE_PHIEU_DAT_PHONG,
    BOOK_ROOM_TRANSACTION,

    // Dịch vụ
    GET_ALL_DICH_VU, GET_DICH_VU_BY_ID, ADD_DICH_VU, UPDATE_DICH_VU, DELETE_DICH_VU,

    // Hóa đơn
    GET_HOA_DON_BY_DATE_RANGE, GET_TOTAL_SERVICE_REVENUE_BY_DATE_RANGE,
    GET_HOA_DON_BY_PHIEU_DAT, CALCULATE_INVOICE_AT_CHECKOUT, ADD_HOA_DON,

    // Chi tiết hóa đơn
    GET_ALL_CHI_TIET_HOA_DON, GET_CHI_TIET_HOA_DON_BY_ID,
    ADD_CHI_TIET_HOA_DON, UPDATE_CHI_TIET_HOA_DON, DELETE_CHI_TIET_HOA_DON,
    GET_CHI_TIET_HOA_DON_BY_HOA_DON, GET_CHI_TIET_BY_MA_PHIEU,
    ADD_OR_UPDATE_CHI_TIET, DELETE_BY_HOA_DON,

    // Nhân viên
    GET_ALL_NHAN_VIEN, GET_NHAN_VIEN_BY_ID, GET_NHAN_VIEN_BY_SDT,
    ADD_NHAN_VIEN, UPDATE_NHAN_VIEN, DELETE_NHAN_VIEN, GENERATE_MA_NHAN_VIEN,

    // Ca làm việc, phân công
    GET_ALL_CA_LAM_VIEC, GET_ALL_PHAN_CONG, SAVE_PHAN_CONG, DELETE_PHAN_CONG,

    // Báo cáo
    GET_ALL_BAO_CAO, SAVE_BAO_CAO, UPDATE_BAO_CAO,

    // TraPhongService (nếu có interface riêng)
    GET_PHIEU_DANG_O, LOAD_PHIEU_DETAIL, GET_CHI_TIET_DICH_VU,
    CALCULATE_CHECKOUT_INVOICE, CONFIRM_CHECKOUT,

    CHECKOUT_TRANSACTION,

    // Bổ sung cho chức năng Yêu cầu phê duyệt
    TAO_YEU_CAU,
    DUYET_YEU_CAU,
    GET_YEU_CAU_CHUA_DUYET,

    PHAT_SINH_MA_PHIEU_MOI,

    UPDATE_PHAN_CONG,

    UPDATE_PHONG_TRANG_THAI,

    GET_ALL_HOA_DON,


}